services:
  loadbalancer:
    image: nginx:1.27.5-alpine-slim
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - client
      - server
      - text-service
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - text-service
    networks:
      - app-network

  text-service:
    build:
      context: ./text-service/api
      dockerfile: Dockerfile.api
    depends_on:
      - redis
    networks:
      - app-network

  text-worker:
    build:
      context: ./text-service/worker
      dockerfile: Dockerfile.worker
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
