services:
  loadbalancer:
    image: nginx:1.27.5-alpine-slim
    expose:
      - "80"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - client
      - text-api
    networks:
      - app-network
    container_name: loadbalancer

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    networks:
      - app-network
    container_name: client
    env_file:
      - .env.production
    environment:
      - VITE_SERVER_BASE_URL={VITE_SERVER_BASE_URL}

  text-api:
    build:
      context: ./text-service/api
      dockerfile: Dockerfile.prod
    networks:
      - app-network
    container_name: text-api
    env_file:
      - .env.production
    environment:
      - DATABASE_URL=${DATABASE_URL} # Pass prod DB URL here

networks:
  app-network:
    # external: true
