services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
    env_file:
      - .env.development
    networks:
      - app-network
    ports:
      - "5173:5173"
    depends_on:
      - text-api

  text-api:
    container_name: text-api
    build:
      context: ./text-service/api
      dockerfile: Dockerfile.dev
    volumes:
      - ./text-service/api:/app
    env_file:
      - .env.development
    networks:
      - app-network
    ports:
      - "5000:5000"

networks:
  app-network:
    driver: bridge
