services:
  loadbalancer:
    container_name: loadbalancer
    image: nginx:1.27.5-alpine-slim
    expose:
      - "80"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - client
      - text-api
    networks:
      - app-network

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    networks:
      - app-network
    env_file:
      - .env.production
    depends_on:
      - text-api

  text-api:
    container_name: text-api
    build:
      context: ./text-service/api
      dockerfile: Dockerfile.prod
    networks:
      - app-network
    env_file:
      - .env.production

networks:
  app-network:
    # external: true
