services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
    env_file:
      - .env.development
    networks:
      - app-network
    ports:
      - "5173:5173"
    depends_on:
      - text-api

  text-api:
    build:
      context: ./text-service/api
      dockerfile: Dockerfile.dev
    volumes:
      - ./text-service/api:/app
    env_file:
      - .env.development
    networks:
      - app-network
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:17.0-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
