services:
  loadbalancer:
    image: nginx:1.27.5-alpine-slim
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - client
      - server
      - text-service
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - text-service
    networks:
      - app-network

  text-service:
    build:
      context: ./text-service/api
      dockerfile: api.Dockerfile
    depends_on:
      - redis
    networks:
      - app-network

  text-worker:
    build:
      context: ./text-service/worker
      dockerfile: worker.Dockerfile
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - app-network

  db:
    image: postgres:17.0-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    # ports:
    #   - "5050:5050"

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
